//
// This file is part of Open Mail.dat.
// Copyright (c) 2025 Open Mail.dat. All rights reserved.
//
// ************************************************************************************************************************
// License Agreement:
//
// Open Mail.dat is free software: you can redistribute it and/or modify it under the terms of the
// GNU LESSER GENERAL PUBLIC LICENSE as published by the Free Software Foundation, either version 3
// of the License, or (at your option) any later version.
// Open Mail.dat is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
// even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU LESSER GENERAL PUBLIC LICENSE for more details.
// You should have received three files as part of the license agreemen for Open Mail.dat.
//
// LICENSE.md (GNU Lesser General Public License)
// LICENSE-GPL3.md (GNU General Public License)
// LICENSE-ADDENDUM.md (Attribution and Public Use Addendum to the GNU Lesser General Public License v3.0 (LGPL-3.0))
//
// If not, see <https://www.gnu.org/licenses/>.
// ************************************************************************************************************************
//
// This code was auto-generated on July 9th, 2025 by the Open Mail.dat Code Generator.
// Code Generator Author: Daniel M porrey
//
namespace Mail.dat
{
	/// <summary>
	/// Is used to capture the header information that is present on the Certificate of Mailing Form.
	/// Provides the header information that is present on the Certificate of Mailing Forms.
	/// </summary>
	public interface IChr : IMaildatEntity 
	{
		/// <summary>
		/// Job ID (CHR-1001)
		/// (Zero fill prior to numeric, if numeric only). See Header File’s Job Id.
		/// </summary>
		string JobId { get; set; }

		/// <summary>
		/// Certificate of Mailing Header ID (CHR-1002)
		/// Unique ID of the Certificate of Mailing Header Record.
		/// </summary>
		string CertificateOfMailingHeaderId { get; set; }

		/// <summary>
		/// Form Type (CHR-1101)
		/// </summary>
		string FormType { get; set; }

		/// <summary>
		/// Sender Tracking ID (CHR-1102)
		/// Unique ID generated by the sender.
		/// </summary>
		string SenderTrackingId { get; set; }

		/// <summary>
		/// Presort Mailing Job ID (CHR-1103)
		/// Job ID of Presort Mailing.
		/// </summary>
		string PresortMailingJobId { get; set; }

		/// <summary>
		/// Presort Mailing User License Code (CHR-1104)
		/// ULC documented in the Presort Mailing job referenced by Presort Mailing Job ID.  Must - begin with
		/// an alpha, be four characters, have no spaces, have no special characters, not be case sensitive.
		/// </summary>
		string PresortMailingUserLicenseCode { get; set; }

		/// <summary>
		/// Mail Owner Contact Name (CHR-1105)
		/// Ex: John Smith. Name of individual for contact support for this Form.
		/// </summary>
		string MailOwnerContactName { get; set; }

		/// <summary>
		/// Mail Owner Company Name (CHR-1106)
		/// Name of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerCompanyName { get; set; }

		/// <summary>
		/// Mail Owner Secondary Address (CHR-1107)
		/// Secondary Address of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerSecondaryAddress { get; set; }

		/// <summary>
		/// Mail Owner Primary Address (CHR-1108)
		/// Primary Address of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerPrimaryAddress { get; set; }

		/// <summary>
		/// Mail Owner City (CHR-1109)
		/// City of Organization that owns the records and the Form.
		/// </summary>
		string MailOwnerCity { get; set; }

		/// <summary>
		/// Mail Owner State (CHR-1110)
		/// State of Organization that owns the records and the Form. Required for addresses in the United
		/// States.
		/// </summary>
		string MailOwnerState { get; set; }

		/// <summary>
		/// Mail Owner Postal Code (CHR-1111)
		/// ZIP Code or Postal Code of Organization that owns the records and the Form. Left Justify; numeric
		/// values of the applicable 5-Digit, or 9-Digit, Barcode for the specific piece. If specifying a
		/// 5-digit barcode, then leave the rest of the field blank.
		/// </summary>
		string MailOwnerPostalCode { get; set; }

		/// <summary>
		/// Mail Owner Province or State - International (CHR-1112)
		/// Province or State of owner's address.  Applicable for international addresses.
		/// </summary>
		string MailOwnerProvinceOrStateInternational { get; set; }

		/// <summary>
		/// Mail Owner Country Code (CHR-1113)
		/// Country Code of owner's address.  When required populated with two-character ISO Country Code. Used
		/// for international addresses only.
		/// </summary>
		string MailOwnerCountryCode { get; set; }

		/// <summary>
		/// Mailing Date (CHR-1114)
		/// The date on which postage is paid to the USPS and verification is completed.
		/// </summary>
		DateOnly? MailingDate { get; set; }

		/// <summary>
		/// Certificate Status (CHR-1115)
		/// </summary>
		string CertificateStatus { get; set; }

		/// <summary>
		/// MPA ID (CHR-1116)
		/// Identify the permit paying for the Certificate of Mailing fees.
		/// </summary>
		string MpaId { get; set; }

		/// <summary>
		/// Flex Option A (CHR-1117)
		/// Reserve Option.
		/// </summary>
		string FlexOptionA { get; set; }

		/// <summary>
		/// Flex Option B (CHR-1118)
		/// Reserve Option.
		/// </summary>
		string FlexOptionB { get; set; }

		/// <summary>
		/// Flex Option C (CHR-1119)
		/// Reserve Option.
		/// </summary>
		string FlexOptionC { get; set; }

		/// <summary>
		/// Reserve (CHR-1120)
		/// Reserved for future use.
		/// </summary>
		string ReserveChr1120 { get; set; }

		/// <summary>
		/// CHR Record Status (CHR-2000)
		/// O, D, I, U.
		/// </summary>
		string ChrRecordStatus { get; set; }

		/// <summary>
		/// Closing Character (CHR-9999)
		/// Must be the # sign.
		/// </summary>
		string ClosingCharacter { get; }

		/// <summary>
		/// Verification Facility Name (CHR-1121)
		/// Name of Mailing Facility where verification occurs.
		/// </summary>
		string VerificationFacilityName { get; set; }

		/// <summary>
		/// Verification Facility ZIP Code (CHR-1122)
		/// ZIP Code of Post Office where postage statement will be finalized (the associated BMEU, not the
		/// DMU).
		/// </summary>
		string VerificationFacilityZipCode { get; set; }
	}
}